export type Project = {
  cate: "creative" | "commercial";
  mediaSrc: string;
  name: string;
  slug: string;
  galleryMedia?: string[];
};

export const projects: Project[] = [
  {
    cate: "creative",
    mediaSrc: "/projects/ALEX NOIRET/ALEXNOIRET_CF128065_ESS_website.jpg",
    name: "ALEX NOIRET",
    slug: "alex-noiret",
    galleryMedia: [
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128065_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128141_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128153_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128199_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128220_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128223_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128254_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128274_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128299_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128329_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128331_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128450_ESS_website.jpg",
      "/projects/ALEX NOIRET/ALEXNOIRET_CF128497_ESS_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc: "/projects/ASHANTI/082317ASHANTI_ESS2445_website.jpg",
    name: "ASHANTI",
    slug: "ashanti",
    galleryMedia: [
      "/projects/ASHANTI/082317ASHANTI_ESS2445_website.jpg",
      "/projects/ASHANTI/082317ASHANTI_ESS2576NEW_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/AVA MAX/110420AVAMAX-HOS_ESS2357finals_website.jpg",
    name: "AVA MAX",
    slug: "ava-max",
    galleryMedia: [
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2357finals_website.jpg",
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2616_website.jpg",
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2665finals_website.jpg",
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2675finals_website.jpg",
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2758finals_website.jpg",
      "/projects/AVA MAX/110420AVAMAX-HOS_ESS2818finals_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc:
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0213finals_website.jpg",
    name: "BAI LAN for FLAUNT",
    slug: "bai-lan-for-flaunt",
    galleryMedia: [
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0213finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0516finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0588finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0616finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS0920finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS1081finals_website.jpg",
      "/projects/BAI LAN for FLAUNT/091522FLAUNT-BAILAN_ESS1307finals_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc: "/projects/BEAR/BEAR_CF128526_ESSfinals_website.jpg",
    name: "BEAR",
    slug: "bear",
    galleryMedia: [
      "/projects/BEAR/BEAR_CF128526_ESSfinals_website.jpg",
      "/projects/BEAR/BEAR_CF128729_ESSfinals_website.jpg",
      "/projects/BEAR/BEAR_CF128794_ESSfinals_website.jpg",
      "/projects/BEAR/BEAR_CF128853_ESSfinals_website.jpg",
      "/projects/BEAR/BEAR_CF129048_ESSfinals_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/BEAUTY/012218BEAUTY_ESS01617Finals2_website.jpg",
    name: "BEAUTY",
    slug: "beauty",
    galleryMedia: ["/projects/BEAUTY/012218BEAUTY_ESS01617Finals2_website.jpg"],
  },
  {
    cate: "commercial",
    mediaSrc: "/projects/BLACK DECKER/0.jpg",
    name: "BLACK & DECKER",
    slug: "black-decker",
    galleryMedia: [
      "/projects/BLACK DECKER/0.jpg",
      "/projects/BLACK DECKER/1.jpg",
      "/projects/BLACK DECKER/2.jpg",
      "/projects/BLACK DECKER/3.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/BRADLEY SOILEAU for GLASSBOOK/s-l1600 copy.jpg",
    name: "BRADLEY SOILEAU for GLASSBOOK",
    slug: "bradley-soileau-for-glassbook",
    galleryMedia: [
      "/projects/BRADLEY SOILEAU for GLASSBOOK/s-l1600 copy.jpg",
      "/projects/BRADLEY SOILEAU for GLASSBOOK/_MG_1875_website.jpg",
      "/projects/BRADLEY SOILEAU for GLASSBOOK/_MG_2962_website.jpg",
      "/projects/BRADLEY SOILEAU for GLASSBOOK/_MG_3103_website.jpg",
      "/projects/BRADLEY SOILEAU for GLASSBOOK/_MG_3335 copy_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc:
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_0146_ESSfinals2_website.jpg",
    name: "BRAVE NEW WORLD for FLAUNT",
    slug: "brave-new-world-for-flaunt",
    galleryMedia: [
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_0146_ESSfinals2_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_8702 2_ESSfinals_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_8801 1_ESSfinals_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_9142_ESSfinals2_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_9208 1_ESSfinals_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_9404_ESSfinals2_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_9706 1_ESSfinals_website.jpg",
      "/projects/BRAVE NEW WORLD for FLAUNT/011322FLAUNT-BNW_ESS_G3_9716_ESSfinals_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc:
      "/projects/CASAMIGOS FIFA 26/051726CASAMIGOS2_ESS_S7A2600final_website.jpg",
    name: "CASAMIGOS FIFA 26",
    slug: "casamigos-fifa-26",
    galleryMedia: [
      "/projects/CASAMIGOS FIFA 26/051726CASAMIGOS2_ESS_S7A2600final_website.jpg",
      "/projects/CASAMIGOS FIFA 26/051726CASAMIGOS_ESS114618final copy_website.jpg",
      "/projects/CASAMIGOS FIFA 26/051726CASAMIGOS_ESS114852final 1_website.jpg",
      "/projects/CASAMIGOS FIFA 26/260512 Casamigos6284final-2_website.jpg",
      "/projects/CASAMIGOS FIFA 26/260512_Casamigos_handheld_0166final_website.jpg",
      "/projects/CASAMIGOS FIFA 26/260512_Casamigos_Phase_0019final_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc:
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40321finals_website.jpg",
    name: "CASAMIGOS RTD HOLIDAY 25",
    slug: "casamigos-rtd-holiday-25",
    galleryMedia: [
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40321finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40409finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40442finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40479finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/111425CASAMIGOS_ESS40516finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0079 - Shot 01finals-editv3_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0224 - Shot 01finals-edit_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0461 - Shot 01finals-editv2-4x5_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0492 - Shot 02finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0571 - Shot 02finals-editv2_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v0936 - Shot 04finals_website.jpg",
      "/projects/CASAMIGOS RTD HOLIDAY 25/ES - Casamigos - 2025.06.10 - v1100 - Shot 04finals-editv2_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc:
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS0360finals_website.jpg",
    name: "CHARLY JORDAN for GALORE",
    slug: "charly-jordan-for-galore",
    galleryMedia: [
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS0360finals_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS0504finals-2_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS0753finals_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS1132finals_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS1197finals copy_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS1252finals_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS1329finals-1_website.jpg",
      "/projects/CHARLY JORDAN for GALORE/041724CHARLYJORDAN-GALORE_ESS1376finals-2_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc:
      "/projects/CLARA BERRY/062123CLARA_ESS0306final-2 copy_new_website.jpg",
    name: "CLARA BERRY",
    slug: "clara-berry",
    galleryMedia: [
      "/projects/CLARA BERRY/062123CLARA_ESS0306final-2 copy_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS0399final-2_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS0422final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS0489final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS0882final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS0957final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1168final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1200final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1261final_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1488final_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1591final_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1687final_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1793finals copy_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1884finals-1_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS1936finals_new_website.jpg",
      "/projects/CLARA BERRY/062123CLARA_ESS2119finals_new_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/DAVID ARQUETTE/0.jpg",
    name: "DAVID ARQUETTE & FRIENDS in HOT TROPICS for FLAUNT",
    slug: "david-arquette-friends-in-hot-tropics-for-flaunt",
    galleryMedia: [
      "/projects/DAVID ARQUETTE/0.jpg",
      "/projects/DAVID ARQUETTE/1.jpg",
      "/projects/DAVID ARQUETTE/2.jpg",
      "/projects/DAVID ARQUETTE/3.jpg",
      "/projects/DAVID ARQUETTE/4.jpg",
      "/projects/DAVID ARQUETTE/5.jpg",
      "/projects/DAVID ARQUETTE/6.jpg",
      "/projects/DAVID ARQUETTE/7.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/DES PIERROT/102620DES_G3_3840_ESSfinals_website.jpg",
    name: "DES PIERROT",
    slug: "des-pierrot",
    galleryMedia: [
      "/projects/DES PIERROT/102620DES_G3_3840_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4096_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4250_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4324_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4521_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4566_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4577_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4753_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4798_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_4931_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5125_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5187_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5356_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5486_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5548_ESSfinals_website.jpg",
      "/projects/DES PIERROT/102620DES_G3_5666_ESSfinals_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc: "/projects/FREE AF/091823FREEAF_ESS22771finals_website.jpg",
    name: "FREE AF",
    slug: "free-af",
    galleryMedia: [
      "/projects/FREE AF/091823FREEAF_ESS22771finals_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS22815finals-edit_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS22833finals-edit_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS22859finals-edit_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS22958finals-edit copy_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS23038finals-edit_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS23242finals-edit_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS23292finals_website.jpg",
      "/projects/FREE AF/091823FREEAF_ESS23403finals-edit_website.jpg",
    ],
  },
  {
    cate: "commercial",
    mediaSrc:
      "/projects/GODDESSES for GAY TIMES/072119GAYTIMES_ESS-CF136967finals_website.jpg",
    name: "GODDESSES for GAY TIMES",
    slug: "goddesses-for-gay-times",
    galleryMedia: [
      "/projects/GODDESSES for GAY TIMES/072119GAYTIMES_ESS-CF136967finals_website.jpg",
      "/projects/GODDESSES for GAY TIMES/072119GAYTIMES_ESS-CF137325finals_website.jpg",
      "/projects/GODDESSES for GAY TIMES/072119GAYTIMES_ESS-CF137976finals_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc:
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_04690033Final_website.jpg",
    name: "NATIONWIDE TERROR for FLAUNT",
    slug: "nationwide-terror-for-flaunt",
    galleryMedia: [
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_04690033Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_2850Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_3418Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_3496Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_3841Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_3891Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4005Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4110Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4328Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4368Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4406Final_website.jpg",
      "/projects/NATIONWIDE TERROR for FLAUNT/102516FLAUNT-MaxRClown_ESS_MG_4755Final_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/projects/PHOEBE DAHL for GLASSBOOK/PHOEBE 5_website.jpg",
    name: "PHOEBE DAHL for GLASSBOOK",
    slug: "phoebe-dahl-for-glassbook",
    galleryMedia: [
      "/projects/PHOEBE DAHL for GLASSBOOK/PHOEBE 5_website.jpg",
      "/projects/PHOEBE DAHL for GLASSBOOK/PHOEBE 7_website.jpg",
      "/projects/PHOEBE DAHL for GLASSBOOK/Water Image 1_3rd Edit_website.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc:
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS6841finals_website.jpg",
    name: "SHERYL LEE RALPH for THE ADVOCATE",
    slug: "sheryl-lee-ralph-for-the-advocate",
    galleryMedia: [
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS6841finals_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS7017finals_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS7310finals copy_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS7580finals_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS7676finals_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS7690finals_website.jpg",
      "/projects/SHERYL LEE RALPH for THE ADVOCATE/110524ADVOCATE-SLR_ESS8154finals_website.jpg",
    ],
  },
];
