export type Project = {
  cate: "creative" | "commerical";
  mediaSrc: string;
  name: string;
  slug: string;
  galleryMedia?: string[];
};

export const projects: Project[] = [
  {
    cate: "creative",
    mediaSrc: "/media/0.jpg",
    name: "Project Aurora",
    slug: "project-aurora",
    galleryMedia: [
      "/media/22.jpg",
      "/media/12.jpg",
      "/media/32.jpg",
      "/media/10.jpg",
      "/media/20.jpg",
      "/media/30.jpg",
    ],
  },
  {
    cate: "creative",
    mediaSrc: "/media/1.jpg",
    name: "Neon Dreams",
    slug: "neon-dreams",
    galleryMedia: ["/media/56.jpg", "/media/36.jpg"],
  },
  {
    cate: "creative",
    mediaSrc: "/media/2.jpg",
    name: "Silent Echo",
    slug: "silent-echo",
    galleryMedia: ["/media/37.jpg", "/media/38.jpg", "/media/8.jpg"],
  },
  {
    cate: "creative",
    mediaSrc: "/media/3.jpg",
    name: "Golden Frame",
    slug: "golden-frame",
  },
  {
    cate: "creative",
    mediaSrc: "/media/4.jpg",
    name: "Midnight Canvas",
    slug: "midnight-canvas",
  },
  {
    cate: "creative",
    mediaSrc: "/media/5.jpg",
    name: "Urban Mirage",
    slug: "urban-mirage",
  },
  {
    cate: "creative",
    mediaSrc: "/media/6.jpg",
    name: "Velvet Sky",
    slug: "velvet-sky",
  },
  {
    cate: "creative",
    mediaSrc: "/media/7.jpg",
    name: "Crimson Flow",
    slug: "crimson-flow",
  },
  {
    cate: "creative",
    mediaSrc: "/media/8.jpg",
    name: "Hidden Light",
    slug: "hidden-light",
  },
  {
    cate: "creative",
    mediaSrc: "/media/9.jpg",
    name: "Blue Horizon",
    slug: "blue-horizon",
  },
  {
    cate: "creative",
    mediaSrc: "/media/10.jpg",
    name: "Dream Sequence",
    slug: "dream-sequence",
  },
  {
    cate: "creative",
    mediaSrc: "/media/11.jpg",
    name: "Glass Motion",
    slug: "glass-motion",
  },
  {
    cate: "creative",
    mediaSrc: "/media/12.jpg",
    name: "Echo Lines",
    slug: "echo-lines",
  },
  {
    cate: "creative",
    mediaSrc: "/media/13.jpg",
    name: "Pixel Bloom",
    slug: "pixel-bloom",
  },
  {
    cate: "creative",
    mediaSrc: "/media/14.jpg",
    name: "Nova Pulse",
    slug: "nova-pulse",
  },
  {
    cate: "creative",
    mediaSrc: "/media/15.jpg",
    name: "Soft Shadows",
    slug: "soft-shadows",
  },
  {
    cate: "creative",
    mediaSrc: "/media/16.jpg",
    name: "Infinite Drift",
    slug: "infinite-drift",
  },
  {
    cate: "creative",
    mediaSrc: "/media/17.jpg",
    name: "Silver Lining",
    slug: "silver-lining",
  },
  {
    cate: "creative",
    mediaSrc: "/media/18.jpg",
    name: "Parallel Fade",
    slug: "parallel-fade",
  },
  {
    cate: "creative",
    mediaSrc: "/media/19.jpg",
    name: "Obsidian Glow",
    slug: "obsidian-glow",
  },
  {
    cate: "creative",
    mediaSrc: "/media/20.jpg",
    name: "Lunar Threads",
    slug: "lunar-threads",
  },
  {
    cate: "creative",
    mediaSrc: "/media/21.jpg",
    name: "Prism Field",
    slug: "prism-field",
  },
  {
    cate: "creative",
    mediaSrc: "/media/22.jpg",
    name: "Flux State",
    slug: "flux-state",
  },
  {
    cate: "creative",
    mediaSrc: "/media/23.jpg",
    name: "Radiant Void",
    slug: "radiant-void",
  },
  {
    cate: "creative",
    mediaSrc: "/media/24.jpg",
    name: "Aurora Shift",
    slug: "aurora-shift",
  },
  {
    cate: "creative",
    mediaSrc: "/media/25.jpg",
    name: "Frozen Frame",
    slug: "frozen-frame",
  },
  {
    cate: "creative",
    mediaSrc: "/media/26.jpg",
    name: "Electric Bloom",
    slug: "electric-bloom",
  },
  {
    cate: "creative",
    mediaSrc: "/media/27.jpg",
    name: "Solar Whisper",
    slug: "solar-whisper",
  },

  {
    cate: "commerical",
    mediaSrc: "/media/28.jpg",
    name: "Brand Elevate",
    slug: "brand-elevate",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/29.jpg",
    name: "Market Pulse",
    slug: "market-pulse",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/30.jpg",
    name: "Ad Spectrum",
    slug: "ad-spectrum",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/31.jpg",
    name: "Vision Boost",
    slug: "vision-boost",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/32.jpg",
    name: "Product Prime",
    slug: "product-prime",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/33.jpg",
    name: "Launch Pad",
    slug: "launch-pad",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/34.jpg",
    name: "Sales Drive",
    slug: "sales-drive",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/35.jpg",
    name: "Growth Engine",
    slug: "growth-engine",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/36.jpg",
    name: "Ad Catalyst",
    slug: "ad-catalyst",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/37.jpg",
    name: "Impact Studio",
    slug: "impact-studio",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/38.jpg",
    name: "Promo Wave",
    slug: "promo-wave",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/39.jpg",
    name: "Conversion Lab",
    slug: "conversion-lab",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/40.jpg",
    name: "Retail Spark",
    slug: "retail-spark",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/41.jpg",
    name: "Ad Horizon",
    slug: "ad-horizon",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/42.jpg",
    name: "Brand Forge",
    slug: "brand-forge",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/43.jpg",
    name: "Market Sync",
    slug: "market-sync",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/44.jpg",
    name: "Campaign Core",
    slug: "campaign-core",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/45.jpg",
    name: "Ad Motion",
    slug: "ad-motion",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/46.jpg",
    name: "Sales Orbit",
    slug: "sales-orbit",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/47.jpg",
    name: "Brand Lift",
    slug: "brand-lift",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/48.jpg",
    name: "Ad Fusion",
    slug: "ad-fusion",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/49.jpg",
    name: "Growth Lab",
    slug: "growth-lab",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/50.jpg",
    name: "Market Edge",
    slug: "market-edge",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/51.jpg",
    name: "Ad Velocity",
    slug: "ad-velocity",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/52.jpg",
    name: "Promo Engine",
    slug: "promo-engine",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/53.jpg",
    name: "Brand Pulse",
    slug: "brand-pulse",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/54.jpg",
    name: "Ad Matrix",
    slug: "ad-matrix",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/55.jpg",
    name: "Conversion Boost",
    slug: "conversion-boost",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/56.jpg",
    name: "Retail Flow",
    slug: "retail-flow",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/57.jpg",
    name: "Campaign Drive",
    slug: "campaign-drive",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/58.jpg",
    name: "Brand Sync",
    slug: "brand-sync",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/59.jpg",
    name: "Ad Sphere",
    slug: "ad-sphere",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/60.jpg",
    name: "Growth Wave",
    slug: "growth-wave",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/61.jpg",
    name: "Market Boost",
    slug: "market-boost",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/62.jpg",
    name: "Ad Engine X",
    slug: "ad-engine-x",
  },
  {
    cate: "commerical",
    mediaSrc: "/media/63.jpg",
    name: "Promo Pulse",
    slug: "promo-pulse",
  },

  {
    cate: "creative",
    mediaSrc: "/media/64.jpg",
    name: "Zenith Flow",
    slug: "zenith-flow",
  },
  {
    cate: "creative",
    mediaSrc: "/media/65.jpg",
    name: "Cosmic Drift",
    slug: "cosmic-drift",
  },
  {
    cate: "creative",
    mediaSrc: "/media/66.jpg",
    name: "Neon Horizon",
    slug: "neon-horizon",
  },
  {
    cate: "creative",
    mediaSrc: "/media/67.jpg",
    name: "Shadow Play",
    slug: "shadow-play",
  },
  {
    cate: "creative",
    mediaSrc: "/media/68.jpg",
    name: "Crystal Echo",
    slug: "crystal-echo",
  },
  {
    cate: "creative",
    mediaSrc: "/media/69.jpg",
    name: "Aurora Lines",
    slug: "aurora-lines",
  },
  {
    cate: "creative",
    mediaSrc: "/media/54.jpg",
    name: "Dream Flow X",
    slug: "dream-flow-x",
  },
  {
    cate: "creative",
    mediaSrc: "/media/55.jpg",
    name: "Light Spectrum",
    slug: "light-spectrum",
  },
];
//minimum range 36
